apiVersion: v1
kind: Service
metadata:
  namespace: ns-mytictactoe
  name: tictactoe-service
  labels:
    app: tictactoe
spec:
  selector:
    app: tictactoe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30026
  type: NodePort